travis:
  secure:
    BINSTAR_TOKEN: kt87YMxHq1c40lB46c6R2QBsUqHXp33MVRWvPFyC/XthU5yEJWwsw9Yjp3HBZQpc88LdkJ990166b3FzU4TvRIHVLxWl8xvGXUjOjtPUQ+czzbxvfYaa9rfr7Y+vs70ytIhyc+DUdA4SddUjoOv7T/MX51WpfTcrUvXaFOqOf+gzkxp66HQm7A8VWET9v9qMWrxDrru4DIKvUBEUpRhtzsgnXIvO0dg6YeESUk8yjqT5uUxXmkTVYxu74HqP127egPdPhsLubWgsy5AciIz5Sst1ufKUuCM11XIYivfkgt6cv+xFtGRluJsr+wM6C06ZmYojwQ7VAWgk775j4eZp2S5KRpbxrOAzzaZ7i5Lk2yqSHdbGy1ZApEQDKjGBpCaKQd60bMGbYlwvXYrJVuvxiU1qp4LBu4bTMzP6iobg0SxoHWzCUbxPFEVcqar8A+XpbgRBD6CasN4YwBuwYyujmDg9KCq6QAe3GBv19N2UFIdc2UAgLp+1t9J9VW3F9fRRzTxbd9PkVlvznG482O1FXO3olLkkAHqplDOql6+aGixdjQKFw+lh0m4cNSvSt9dS/uhiOEch1fKn9FjscPRSPl6fxoV2beVw4z+raW1+iM2pZlWGSHaEnf9k0nSg8TVDuuMwOAU/33/4iu0I4BpvMofZRxPbiHMBQx1JtD2sw2c=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
